# Generated by Django 5.2.4 on 2025-07-21 01:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_person_email_alter_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[accounts.models.validate_image_extension]),
        ),
    ]
