# Generated by Django 5.2.3 on 2025-07-23 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only alphabetic characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
