# Generated by Django 5.2.4 on 2025-07-18 01:30

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('problem_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Extreme', 'Extreme')], max_length=10)),
                ('problem_desc', tinymce.models.HTMLField()),
                ('test_cases', models.FileField(help_text='Upload JSON file with input/output test cases', upload_to='testcases/')),
                ('max_runtime', models.FloatField(help_text='Max allowed runtime in seconds')),
                ('max_memory', models.IntegerField(help_text='Max allowed memory in MB')),
                ('problem_runtime', models.FloatField(blank=True, help_text='Actual runtime in seconds', null=True)),
                ('problem_memory', models.IntegerField(blank=True, help_text='Actual memory in MB', null=True)),
                ('previous_submissions', models.JSONField(blank=True, default=dict)),
                ('rating_to_problem', models.IntegerField(default=0, null=True)),
                ('points_awarded', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('total_submissions', models.IntegerField(default=0)),
                ('successful_submissions', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0, help_text='Percentage of users who successfully solved the problem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
                'ordering': ['-created_at'],
            },
        ),
    ]
