# Generated by Django 5.2.4 on 2025-07-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_set', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='rating_to_problem',
            field=models.IntegerField(default=0, max_length=5, null=True),
        ),
    ]
