# Generated by Django 5.2.4 on 2025-07-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_set', '0002_alter_problems_rating_to_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='rating_to_problem',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, null=True),
        ),
    ]
