# Generated by Django 5.2.4 on 2025-07-18 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem_set', '0003_alter_problems_rating_to_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problems',
            old_name='problem_id',
            new_name='id',
        ),
    ]
