# Generated by Django 5.2.4 on 2025-07-18 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem_set', '0004_rename_problem_id_problems_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compiler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('input_tests', models.TextField(null=True)),
                ('output', models.TextField(null=True)),
                ('verdicts', models.CharField(max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('runtime', models.FloatField(null=True)),
                ('memory_used', models.FloatField(null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problem_set.problems')),
            ],
        ),
    ]
